spring:
  profiles:
    active: dev
--- 
 spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/dev
  profiles: dev    
---

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/prod
  profiles: prod
    
 
 
   
